protected/models/Cliente.php
<?php  

class Cliente extends CActiveRecord{

	public static function model($class=__CLASS__){
		return parent::model($class);
	}
	
	public function tableName(){
		return 'cliente';
	}

	public function relations(){
		return array(
			'roles'=>array(self::BELONGS_TO,'Roles','rol')
			);
	}
}
?>

protected/models/ClienteForm.php
<?php 

class ClienteForm extends CFormModel{

	public $nombre;
	public $apellido;
	public $email;
	public $cumpleano;
	public $rol;
	public $fcompare;

	public function rules(){
		return array(
			array('nombre,apellido,email,cumpleano,rol','safe','on'=>'create,update'),
			array('nombre,apellido,email,cumpleano,rol','required','on'=>'create,update'),
			array('nombre,apellido,cumpleano,rol,fcompare','safe','on'=>'search'),
			array('email','email','on'=>'create,update'),
			array('cumpleano','date','format'=>'yyyy-MM-dd','on'=>'create,update')
			);
	}
}

?>

protected/models/RolForm.php
<?php 

class RolForm extends CFormModel{

	public $rol;

	public function rules(){
		return array(
			array('rol','safe'),
			array('rol','required')
			);
	}
}

?>

protected/models/Roles.php
<?php 

class Roles extends CActiveRecord{

	public static function model($class=__CLASS__){
		return parent::model($class);
	}
	
	public function tableName(){
		return 'roles';
	}	
}
?>

protected/controllers/ClienteController.php
<?php 

class ClienteController extends Controller{

	public $layout = 'maincustom';

	public function actionIndex(){
		$this->pageTitle = "Lista de clientes";

		$modelf = new ClienteForm('search');
		$modelf->unsetAttributes();
		if(isset($_GET['ClienteForm'])){
			$modelf->attributes=$_GET['ClienteForm'];
		}
		$model = Roles::model()->findAll();
		$this->render('index',array('model'=>$model,'modelf'=>$modelf));
	}

	public function actionView($id){
		$this->pageTitle = "Ver cliente";
		$c = Cliente::model()->findByPk($id);
		$this->render('leer',array('cliente'=>$c));
	}

	public function actionCreate(){

		$this->pageTitle = "Agregar cliente";
		$model = new ClienteForm('create');

		if(isset($_POST['ClienteForm'])){
			$model->attributes = $_POST['ClienteForm'];
			if($model->validate()){
				$c = new Cliente;
				$c->setAttributes($model->getAttributes(),false);
				$c->save();
				Yii::app()->user->setFlash('success','Cliente agregado exitosamente');
				$this->redirect(Yii::app()->controller->createUrl('/cliente'));
			}
		}

		$this->render('form',array('model'=>$model));
	}

	public function actionDelete($id){

		$c = Cliente::model()->findByPk($id);
		$c->delete();
	}

	public function actionUpdate($id){

		$this->pageTitle = "Edición de cliente";

		$c = Cliente::model()->findByPk($id);

		$model = new ClienteForm('update');
		$model->attributes = $c->getAttributes();
		if(isset($_POST['ClienteForm'])){
			$c->setAttributes($_POST['ClienteForm'],false);
			$c->save();
			Yii::app()->user->setFlash('success','Cliente actualizado');
			$this->redirect(Yii::app()->createUrl('/cliente'));
		}

		$this->render('form',array('model'=>$model));
	}

	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

}
?>

protected/controllers/RolController.php
<?php  

class RolController extends Controller{

	public $layout = 'maincustom';

	public function actionIndex(){
		$this->pageTitle = "Lista de roles";
		$this->render('index');
	}

	public function actionCreate(){
		$this->pageTitle = "Agregar rol";
		$model = new RolForm;

		if(isset($_POST['RolForm'])){
			$model->attributes = $_POST['RolForm'];
			if($model->validate()){
				$r = new Roles;
				$r->setAttributes($_POST['RolForm'],false);
				$r->save();
				$this->redirect(Yii::app()->controller->createUrl('/rol'));
			}
		}
		$this->render('form',array('model'=>$model));
	}

	public function actionUpdate($id){
		$this->pageTitle = "Editar rol";
		$r = Roles::model()->findByPk($id);
		$model = new RolForm;
		$model->attributes = $r->attributes;

		if(isset($_POST['RolForm'])){
			$model->attributes = $_POST['RolForm'];
			if($model->validate()){
				$r->setAttributes($_POST['RolForm'],false);
				$r->save();
				$this->redirect(Yii::app()->controller->createUrl('/rol'));
			}
		}

		$this->render('form',array('model'=>$model));

	}

	public function actionDelete($id){
		$r = Roles::model()->findByPk($id);
		$r->delete();
	}
}
?>

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/cliente/agregar.php
<div class="form container" role="form">
	<?php $form = $this->beginWidget('CActiveForm',array(
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true
			)
		)
	); ?>
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Nombre:'); ?>
	       <?php echo $form->textField($model,'nombre',array('class'=>'form-control')); ?>
	       <?php echo $form->error($model,'nombre'); ?>
	    </div>
	    <div class="form-group col-lg-4">
	        <?php echo $form->label($model,'Apellido:'); ?>
	        <?php echo $form->textField($model,'apellido',array('class'=>'form-control')); ?>
	        <?php echo $form->error($model,'apellido'); ?>
	    </div>
	    <div class="form-group col-lg-4"></div>	
	</div>
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'E-mail:'); ?>
	       <?php echo $form->emailField($model,'email',array('class'=>'form-control')); ?>
	       <?php echo $form->error($model,'email'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>

	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Fecha de nacimiento:'); ?>
	       <?php 
			$this->widget('ext.rezvan.RDatePicker',array(
			'name'=>'ClienteForm[cumpleano]',
			'value'=>'1990-01-01',
			'htmlOptions'=>array('class'=>'form-control','type'=>'text','autocumplete'=>'off'),
			'options' => array(
			'language'=>'es',
			'format' => 'yyyy-mm-dd',
			'viewformat' => 'yyyy-mm-dd',
			'placement' => 'right',
			'todayBtn'=>false
			)
			)); 
			?>
	       <?php echo $form->error($model,'cumpleano'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>
	
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Rol:'); ?>
	       <?php echo $form->dropDownList($model,'rol',CHtml::listData(Roles::model()->findAll(),'idrol','rol'),array('prompt'=>'---Seleccione rol---','class'=>'form-control')); ?>
	       <?php echo $form->error($model,'rol'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>

	<?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-success btn-lg')); ?> <a href="<?php echo Yii::app()->request->baseUrl; ?>" class="btn btn-default btn-lg">Cancelar</a>
	
    
    <?php $this->endWidget(); ?>
</div>

protected/views/cliente/error.php
<h2>Error <?php echo $code; ?></h2>
<?php echo $message; ?>

protected/views/cliente/form.php
<div class="form container" role="form">
	<?php $form = $this->beginWidget('CActiveForm',array(
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true
			)
		)
	); ?>
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Nombre:'); ?>
	       <?php echo $form->textField($model,'nombre',array('class'=>'form-control')); ?>
	       <?php echo $form->error($model,'nombre'); ?>
	    </div>
	    <div class="form-group col-lg-4">
	        <?php echo $form->label($model,'Apellido:'); ?>
	        <?php echo $form->textField($model,'apellido',array('class'=>'form-control')); ?>
	        <?php echo $form->error($model,'apellido'); ?>
	    </div>
	    <div class="form-group col-lg-4"></div>	
	</div>
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'E-mail:'); ?>
	       <?php echo $form->emailField($model,'email',array('class'=>'form-control')); ?>
	       <?php echo $form->error($model,'email'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>

	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Fecha de nacimiento:'); ?>
	       <?php 
			$this->widget('ext.rezvan.RDatePicker',array(
			'name'=>'ClienteForm[cumpleano]',
			'value'=>$model->cumpleano,
			'htmlOptions'=>array('class'=>'form-control','type'=>'text','autocumplete'=>'off'),
			'options' => array(
			'language'=>'es',
			'format' => 'yyyy-mm-dd',
			'viewformat' => 'yyyy-mm-dd',
			'placement' => 'right',
			'todayBtn'=>false
			)
			)); 
			?>
	       <?php echo $form->error($model,'cumpleano'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>
	
	<div class="row">
		<div class="form-group col-lg-4">
	       <?php echo $form->label($model,'Rol:'); ?>
	       <?php echo $form->dropDownList($model,'rol',CHtml::listData(Roles::model()->findAll(),'idrol','rol'),array('prompt'=>'---Seleccione rol---','class'=>'form-control')); ?>
	       <?php echo $form->error($model,'rol'); ?>
	    </div>
	    <div class="form-group col-lg-8"></div>	
	</div>

	<?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-success btn-lg')); ?> <a href="<?php echo Yii::app()->controller->createUrl('/cliente'); ?>" class="btn btn-default btn-lg">Cancelar</a>
	
    
    <?php $this->endWidget(); ?>
</div>

protected/views/cliente/index.php

<div>
	<a href="<?php echo Yii::app()->createUrl('/cliente/create'); ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Agregar cliente</a>
	<br /><br />
</div>
<?php if(Yii::app()->user->hasFlash('success')): ?>
	<div class="alert alert-success alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<?php echo Yii::app()->user->getFlash('success'); ?>
	</div>
<?php endif; ?>
<?php 
	$form = $this->beginWidget('CActiveForm',array('method'=>'get'));
	?>
	<div class="well">
		<strong>Filtro de clientes:</strong><br /><br />
		<div class="row">
			<div class="col-md-4"><?php echo $form->textField($modelf,'nombre',array('class'=>'form-control','placeholder'=>'Nombre:')); ?></div>
			<div class="col-md-4"><?php echo $form->textField($modelf,'apellido',array('class'=>'form-control','placeholder'=>'Apellido:')); ?></div>
			<div class="col-md-4"></div>
		</div>
		<br />
		<div class="row">		
			<div class="col-md-4"><?php echo $form->dropDownList($modelf,'rol',CHtml::listData(Roles::model()->findAll(),'idrol','rol'),array('prompt'=>'---Seleccione rol---','class'=>'form-control')); ?></div>
			<div class="col-md-2"><?php echo $form->dropDownList($modelf,'fcompare',array("="=>"Igual a","<"=>"Menor que","<="=>"Menor igual que",">"=>"Mayor que",">="=>"Mayor igual que"),array('class'=>'form-control')); ?></div>
			<div class="col-md-2">
				<?php 
				$this->widget('ext.rezvan.RDatePicker',array(
				'name'=>'ClienteForm[cumpleano]',
				'value'=>$modelf->cumpleano,
				'htmlOptions'=>array('class'=>'form-control','type'=>'text','autocumplete'=>'off','placeholder'=>'Cumpleaño:'),
				'options' => array(
				'language'=>'es',
				'format' => 'yyyy-mm-dd',
				'viewformat' => 'yyyy-mm-dd',
				'placement' => 'right',
				'todayBtn'=>false
				)
				)); 
				?>
			</div>
			<div class="col-md-4"><?php echo CHtml::submitButton('Filtrar',array('class'=>'btn btn-primary')); ?></div>
		</div>
	</div>

	<?php
	$this->endWidget();

	$criteria = new CDbCriteria;
	$criteria->compare('nombre',$modelf->nombre,true);
	$criteria->compare('apellido',$modelf->apellido,true);
	if(!empty($modelf->fcompare)&&!empty($modelf->cumpleano)){
		$criteria->compare('cumpleano',$modelf->fcompare.' '.$modelf->cumpleano);
	}
	$criteria->compare('rol',$modelf->rol);
	$dataprovider = new CActiveDataProvider('Cliente',array('criteria'=>$criteria,'sort'=>array('defaultOrder'=>'concat(nombre,apellido) ASC'))); 
	$this->widget('zii.widgets.grid.CGridView',array(
		'dataProvider'=>$dataprovider,
		'columns'=>array(
			array(
				'class'=>'CButtonColumn',
				'template'=>'{view}',
				'buttons'=>array(
					'view'=>array(
						'label'=>'',
						'imageUrl'=>'',
						'options'=>array('class'=>'glyphicon glyphicon-eye-open')
						)
					)
				),
			'nombre',
			'apellido',
			'email',
			'cumpleano',
			'roles.rol',
			array('class'=>'CButtonColumn',
				'template'=>'{update} {delete}',
				'buttons'=>array(
					'update'=>array(
						'label'=>'',
						'imageUrl'=>'',
						'options'=>array('class'=>'glyphicon glyphicon-edit')
						),
					'delete'=>array(
						'label'=>'',
						'imageUrl'=>'',
						'options'=>array('class'=>'glyphicon glyphicon-remove')
						)
					)
				)
			)
		));
?>

protected/views/cliente/leer.php
<a href="<?php echo Yii::app()->controller->createUrl('/cliente'); ?>" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left"></span> Volver</a>

<h3><?php echo $cliente->nombre.' '.$cliente->apellido; ?></h3>
<p>
	<b>Email:</b> <?php echo $cliente->email; ?><br />
	<b>Cumpleños:</b> <?php echo $cliente->cumpleano; ?><br />
	<b>Rol:</b> <?php echo $cliente->roles->rol; ?>
</p>

protected/views/layouts/maincustom.php

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">    

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style type="text/css">
    body {
      padding-top: 70px;
      padding-bottom: 20px;
      background: #424D61;
    }

    .navbar {
      margin-bottom: 20px;
    }

    .errorMessage{
      color: red;
    }
    </style>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><?php echo Yii::app()->name; ?></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">            
            <li><a href="<?php echo Yii::app()->createUrl('/cliente'); ?>">Clientes</a></li>
            <li><a href="<?php echo Yii::app()->createUrl('/rol'); ?>">Roles</a></li>
          </ul>          
        </div><!--/.nav-collapse -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><?php echo CHtml::encode($this->pageTitle); ?></h3>
        </div>
        <div class="panel-body"><?php echo $content; ?></div>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
  </body>
</html>

protected/views/rol/form.php
<div class="form container" role="form">
	<?php $form = $this->beginWidget('CActiveForm',array(
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true
			)
		)
	); ?>
	<div class="row">
		<div class="control-group col-lg-4">
		<?php echo $form->label($model,'Rol:'); ?>
		<?php echo $form->textField($model,'rol',array('class'=>'form-control')) ?>
		<?php echo $form->error($model,'rol'); ?>
		</div>
	</div>
	<br />
	<?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-success btn-lg')); ?>
	<a href="<?php echo Yii::app()->controller->createUrl('/rol'); ?>" class="btn btn-default btn-lg">Cancelar</a>
	<?php $this->endWidget(); ?>
</div>

protected/views/rol/index.php
<div>
	<a href="<?php echo Yii::app()->createUrl('/rol/create'); ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Agregar rol</a>
	<br /><br />
</div>

<?php $dataprovider = new CActiveDataProvider('Roles'); 
	  $this->widget('zii.widgets.grid.CGridView',array(
	  	'dataProvider'=>$dataprovider,
	  	'columns'=>array(
	  		'rol',
	  		array('class'=>'CButtonColumn',
	  			'template'=>'{update} {delete}')
	  		)
	  	)
	  );
?>